// front/constants/symbols.ts
// 日本株 (日経225全銘柄)
export const nikkei225Symbols = [
  { label: "ニッスイ", value: "TRADU:1332" },
  { label: "大成建設", value: "TRADU:1801" },
  { label: "大林組", value: "TRADU:1802" },
  { label: "清水建設", value: "TRADU:1803" },
  { label: "長谷工コーポレーション", value: "TRADU:1808" },
  { label: "鹿島建設", value: "TRADU:1812" },
  { label: "大和ハウス工業", value: "TRADU:1925" },
  { label: "積水ハウス", value: "TRADU:1928" },
  { label: "キリンホールディングス", value: "TRADU:2503" },
  { label: "サッポロホールディングス", value: "TRADU:2501" },
  { label: "アサヒグループホールディングス", value: "TRADU:2502" },
  { label: "キッコーマン", value: "TRADU:2801" },
  { label: "味の素", value: "TRADU:2802" },
  { label: "JT", value: "TRADU:2914" },
  { label: "セブン＆アイ・ホールディングス", value: "TRADU:3382" },
  { label: "東洋紡", value: "TRADU:3101" },
  { label: "帝人", value: "TRADU:3401" },
  { label: "東レ", value: "TRADU:3402" },
  { label: "旭化成", value: "TRADU:3407" },
  { label: "王子ホールディングス", value: "TRADU:3861" },
  { label: "日本製紙", value: "TRADU:3863" },
  { label: "レゾナック・ホールディングス", value: "TRADU:4004" },
  { label: "住友化学", value: "TRADU:4005" },
  { label: "日産化学", value: "TRADU:4021" },
  { label: "東ソー", value: "TRADU:4042" },
  { label: "トクヤマ", value: "TRADU:4043" },
  { label: "デンカ", value: "TRADU:4061" },
  { label: "信越化学工業", value: "TRADU:4063" },
  { label: "協和キリン", value: "TRADU:4151" },
  { label: "三井化学", value: "TRADU:4183" },
  { label: "JSR", value: "TRADU:4185" },
  { label: "三菱ケミカルグループ", value: "TRADU:4188" },
  { label: "宇部興産", value: "TRADU:4208" },
  { label: "電通グループ", value: "TRADU:4324" },
  { label: "花王", value: "TRADU:4452" },
  { label: "武田薬品工業", value: "TRADU:4502" },
  { label: "アステラス製薬", value: "TRADU:4503" },
  { label: "塩野義製薬", value: "TRADU:4507" },
  { label: "中外製薬", value: "TRADU:4519" },
  { label: "エーザイ", value: "TRADU:4523" },
  { label: "テルモ", value: "TRADU:4543" },
  { label: "第一三共", value: "TRADU:4568" },
  { label: "大塚ホールディングス", value: "TRADU:4578" },
  { label: "楽天グループ", value: "TRADU:4755" },
  { label: "富士フイルムホールディングス", value: "TRADU:4901" },
  { label: "コニカミノルタ", value: "TRADU:4902" },
  { label: "資生堂", value: "TRADU:4911" },
  { label: "出光興産", value: "TRADU:5019" },
  { label: "ENEOSホールディングス", value: "TRADU:5020" },
  { label: "AGC", value: "TRADU:5201" },
  { label: "日本板硝子", value: "TRADU:5202" },
  { label: "太平洋セメント", value: "TRADU:5233" },
  { label: "TOTO", value: "TRADU:5332" },
  { label: "日本製鉄", value: "TRADU:5401" },
  { label: "神戸製鋼所", value: "TRADU:5406" },
  { label: "JFEホールディングス", value: "TRADU:5411" },
  { label: "日本製鋼所", value: "TRADU:5631" },
  { label: "三井金属鉱業", value: "TRADU:5706" },
  { label: "三菱マテリアル", value: "TRADU:5711" },
  { label: "住友金属鉱山", value: "TRADU:5713" },
  { label: "DOWAホールディングス", value: "TRADU:5714" },
  { label: "古河電気工業", value: "TRADU:5801" },
  { label: "住友電気工業", value: "TRADU:5802" },
  { label: "フジクラ", value: "TRADU:5803" },
  { label: "LIXIL", value: "TRADU:5938" },
  { label: "リクルートホールディングス", value: "TRADU:6098" },
  { label: "オークマ", value: "TRADU:6103" },
  { label: "アマダ", value: "TRADU:6113" },
  { label: "DMG森精機", value: "TRADU:6141" },
  { label: "SMC", value: "TRADU:6273" },
  { label: "コマツ", value: "TRADU:6301" },
  { label: "住友重機械工業", value: "TRADU:6302" },
  { label: "日立建機", value: "TRADU:6305" },
  { label: "クボタ", value: "TRADU:6326" },
  { label: "荏原製作所", value: "TRADU:6361" },
  { label: "ダイキン工業", value: "TRADU:6367" },
  { label: "ブラザー工業", value: "TRADU:6448" },
  { label: "日本精工", value: "TRADU:6471" },
  { label: "NTN", value: "TRADU:6472" },
  { label: "ジェイテクト", value: "TRADU:6473" },
  { label: "日立製作所", value: "TRADU:6501" },
  { label: "東芝", value: "TRADU:6502" },
  { label: "三菱電機", value: "TRADU:6503" },
  { label: "富士電機", value: "TRADU:6504" },
  { label: "安川電機", value: "TRADU:6506" },
  { label: "ニデック", value: "TRADU:6594" },
  { label: "オムロン", value: "TRADU:6645" },
  { label: "GSユアサ コーポレーション", value: "TRADU:6674" },
  { label: "NEC", value: "TRADU:6701" },
  { label: "富士通", value: "TRADU:6702" },
  { label: "OKI", value: "TRADU:6703" },
  { label: "ルネサスエレクトロニクス", value: "TRADU:6723" },
  { label: "セイコーエプソン", value: "TRADU:6724" },
  { label: "パナソニック ホールディングス", value: "TRADU:6752" },
  { label: "シャープ", value: "TRADU:6753" },
  { label: "ソニーグループ", value: "TRADU:6758" },
  { label: "TDK", value: "TRADU:6762" },
  { label: "アルプスアルパイン", value: "TRADU:6770" },
  { label: "横河電機", value: "TRADU:6841" },
  { label: "アドバンテスト", value: "TRADU:6857" },
  { label: "キーエンス", value: "TRADU:6861" },
  { label: "デンソー", value: "TRADU:6902" },
  { label: "カシオ計算機", value: "TRADU:6952" },
  { label: "ファナック", value: "TRADU:6954" },
  { label: "京セラ", value: "TRADU:6971" },
  { label: "太陽誘電", value: "TRADU:6976" },
  { label: "村田製作所", value: "TRADU:6981" },
  { label: "日東電工", value: "TRADU:6988" },
  { label: "三菱重工業", value: "TRADU:7011" },
  { label: "川崎重工業", value: "TRADU:7012" },
  { label: "IHI", value: "TRADU:7013" },
  { label: "コンコルディア・フィナンシャルグループ", value: "TRADU:7186" },
  { label: "日産自動車", value: "TRADU:7201" },
  { label: "いすゞ自動車", value: "TRADU:7202" },
  { label: "トヨタ自動車", value: "TRADU:7203" },
  { label: "日野自動車", value: "TRADU:7205" },
  { label: "三菱自動車工業", value: "TRADU:7211" },
  { label: "マツダ", value: "TRADU:7261" },
  { label: "本田技研工業", value: "TRADU:7267" },
  { label: "スズキ", value: "TRADU:7269" },
  { label: "SUBARU", value: "TRADU:7270" },
  { label: "ヤマハ発動機", value: "TRADU:7272" },
  { label: "HOYA", value: "TRADU:7741" },
  { label: "オリンパス", value: "TRADU:7733" },
  { label: "SCREENホールディングス", value: "TRADU:7735" },
  { label: "キヤノン", value: "TRADU:7751" },
  { label: "リコー", value: "TRADU:7752" },
  { label: "シチズン時計", value: "TRADU:7762" },
  { label: "バンダイナムコホールディングス", value: "TRADU:7832" },
  { label: "TOPPANホールディングス", value: "TRADU:7911" },
  { label: "大日本印刷", value: "TRADU:7912" },
  { label: "ヤマハ", value: "TRADU:7951" },
  { label: "任天堂", value: "TRADU:7974" },
  { label: "伊藤忠商事", value: "TRADU:8001" },
  { label: "丸紅", value: "TRADU:8002" },
  { label: "豊田通商", value: "TRADU:8015" },
  { label: "三井物産", value: "TRADU:8031" },
  { label: "東京エレクトロン", value: "TRADU:8035" },
  { label: "セイコーグループ", value: "TRADU:8050" },
  { label: "住友商事", value: "TRADU:8053" },
  { label: "三菱商事", value: "TRADU:8058" },
  { label: "高島屋", value: "TRADU:8233" },
  { label: "丸井グループ", value: "TRADU:8252" },
  { label: "イオン", value: "TRADU:8267" },
  { label: "三菱UFJフィナンシャル・グループ", value: "TRADU:8306" },
  { label: "りそなホールディングス", value: "TRADU:8308" },
  { label: "三井住友フィナンシャルグループ", value: "TRADU:8316" },
  { label: "千葉銀行", value: "TRADU:8331" },
  { label: "ふくおかフィナンシャルグループ", value: "TRADU:8354" },
  { label: "静岡銀行", value: "TRADU:8355" },
  { label: "みずほフィナンシャルグループ", value: "TRADU:8411" },
  { label: "大和証券グループ本社", value: "TRADU:8601" },
  { label: "野村ホールディングス", value: "TRADU:8604" },
  { label: "SOMPOホールディングス", value: "TRADU:8630" },
  { label: "日本取引所グループ", value: "TRADU:8697" },
  {
    label: "MS&ADインシュアランスグループホールディングス",
    value: "TRADU:8725",
  },
  { label: "第一生命ホールディングス", value: "TRADU:8750" },
  { label: "東京海上ホールディングス", value: "TRADU:8766" },
  { label: "T&Dホールディングス", value: "TRADU:8795" },
  { label: "三菱地所", value: "TRADU:8801" },
  { label: "三井不動産", value: "TRADU:8802" },
  { label: "平和不動産", value: "TRADU:8803" },
  { label: "東京建物", value: "TRADU:8804" },
  { label: "住友不動産", value: "TRADU:8830" },
  { label: "東武鉄道", value: "TRADU:9001" },
  { label: "東急", value: "TRADU:9005" },
  { label: "小田急電鉄", value: "TRADU:9007" },
  { label: "京王電鉄", value: "TRADU:9008" },
  { label: "京成電鉄", value: "TRADU:9009" },
  { label: "JR東日本", value: "TRADU:9020" },
  { label: "JR西日本", value: "TRADU:9021" },
  { label: "JR東海", value: "TRADU:9022" },
  { label: "西武ホールディングス", value: "TRADU:9024" },
  { label: "ヤマトホールディングス", value: "TRADU:9064" },
  { label: "日本郵船", value: "TRADU:9101" },
  { label: "商船三井", value: "TRADU:9104" },
  { label: "川崎汽船", value: "TRADU:9107" },
  { label: "日本航空 (JAL)", value: "TRADU:9201" },
  { label: "ANAホールディングス", value: "TRADU:9202" },
  { label: "日本電信電話 (NTT)", value: "TRADU:9432" },
  { label: "KDDI", value: "TRADU:9433" },
  { label: "ソフトバンク", value: "TRADU:9434" },
  { label: "東京電力ホールディングス", value: "TRADU:9501" },
  { label: "中部電力", value: "TRADU:9502" },
  { label: "関西電力", value: "TRADU:9503" },
  { label: "東京ガス", value: "TRADU:9531" },
  { label: "大阪ガス", value: "TRADU:9532" },
  { label: "NTTデータグループ", value: "TRADU:9613" },
  { label: "SCSK", value: "TRADU:9719" },
  { label: "セコム", value: "TRADU:9735" },
  { label: "ファーストリテイリング", value: "TRADU:9983" },
  { label: "ソフトバンクグループ", value: "TRADU:9984" },
  { label: "ニトリホールディングス", value: "TRADU:9843" },

  { label: "INPEX", value: "TRADU:1605" },
  { label: "メルカリ", value: "TRADU:4385" },
  { label: "レーザーテック", value: "TRADU:6920" },
  { label: "日本郵政", value: "TRADU:6178" },
  { label: "シスメックス", value: "TRADU:6869" },
  { label: "オリエンタルランド", value: "TRADU:4661" },
  { label: "伊藤忠テクノソリューションズ", value: "TRADU:4739" },
  { label: "オリックス", value: "TRADU:8591" },
  { label: "アインホールディングス", value: "TRADU:9627" },
  { label: "東急不動産ホールディングス", value: "TRADU:3289" },
  { label: "オープンハウスグループ", value: "TRADU:3288" },
  { label: "ゆうちょ銀行", value: "TRADU:7182" },
  { label: "かんぽ生命保険", value: "TRADU:7181" },
  { label: "TIS", value: "TRADU:3626" },
  { label: "野村総合研究所", value: "TRADU:4307" },
  { label: "オービック", value: "TRADU:4684" },
  { label: "ネクソン", value: "TRADU:3659" },
  { label: "トレンドマイクロ", value: "TRADU:4704" },
  { label: "エムスリー", value: "TRADU:2413" },
  { label: "サイバーエージェント", value: "TRADU:4751" },
  { label: "DeNA", value: "TRADU:2432" },
  { label: "LINEヤフー", value: "TRADU:4689" },
  { label: "MonotaRO", value: "TRADU:3064" },
  { label: "ZOZO", value: "TRADU:3092" },
  { label: "日本M&Aセンターホールディングス", value: "TRADU:2127" },
  { label: "エスエムエス", value: "TRADU:2175" },
  { label: "ベネッセホールディングス", value: "TRADU:9783" },
  { label: "パーソルホールディングス", value: "TRADU:2181" },
  { label: "ディスコ", value: "TRADU:6146" },
  { label: "ローム", value: "TRADU:6963" },
  { label: "浜松ホトニクス", value: "TRADU:6965" },
  { label: "イビデン", value: "TRADU:4062" },
  { label: "新光電気工業", value: "TRADU:6967" },
  { label: "東宝", value: "TRADU:9602" },
  { label: "松竹", value: "TRADU:9601" },
  { label: "東映", value: "TRADU:9605" },
];

// 米国株 (主要銘柄)
export const usStockSymbols = [
  // NASDAQ
  { label: "Apple", value: "NASDAQ:AAPL" },
  { label: "Microsoft", value: "NASDAQ:MSFT" },
  { label: "Amazon.com", value: "NASDAQ:AMZN" },
  { label: "NVIDIA", value: "NASDAQ:NVDA" },
  { label: "Alphabet (Google)", value: "NASDAQ:GOOGL" },
  { label: "Meta Platforms (Facebook)", value: "NASDAQ:META" },
  { label: "Tesla", value: "NASDAQ:TSLA" },
  { label: "Broadcom", value: "NASDAQ:AVGO" },
  { label: "Costco Wholesale", value: "NASDAQ:COST" },
  { label: "Adobe", value: "NASDAQ:ADBE" },
  { label: "Netflix", value: "NASDAQ:NFLX" },
  { label: "Intel", value: "NASDAQ:INTC" },
  { label: "AMD", value: "NASDAQ:AMD" },
  { label: "PepsiCo", value: "NASDAQ:PEP" },
  { label: "Cisco Systems", value: "NASDAQ:CSCO" },
  { label: "Qualcomm", value: "NASDAQ:QCOM" },
  { label: "Starbucks", value: "NASDAQ:SBUX" },
  { label: "Texas Instruments", value: "NASDAQ:TXN" },
  { label: "Intuitive Surgical", value: "NASDAQ:ISRG" },
  { label: "Micron Technology", value: "NASDAQ:MU" },
  { label: "Moderna", value: "NASDAQ:MRNA" },
  { label: "Applied Materials", value: "NASDAQ:AMAT" },
  { label: "ASML Holding", value: "NASDAQ:ASML" },
  { label: "Comcast", value: "NASDAQ:CMCSA" },
  { label: "PayPal", value: "NASDAQ:PYPL" },
  { label: "Marriott International", value: "NASDAQ:MAR" },
  { label: "Airbnb", value: "NASDAQ:ABNB" },
  // NYSE
  { label: "Berkshire Hathaway (Class B)", value: "NYSE:BRK.B" },
  { label: "Eli Lilly and Company", value: "NYSE:LLY" },
  { label: "Visa", value: "NYSE:V" },
  { label: "JPMorgan Chase & Co.", value: "NYSE:JPM" },
  { label: "Exxon Mobil", value: "NYSE:XOM" },
  { label: "UnitedHealth Group", value: "NYSE:UNH" },
  { label: "Johnson & Johnson", value: "NYSE:JNJ" },
  { label: "Mastercard", value: "NYSE:MA" },
  { label: "Procter & Gamble", value: "NYSE:PG" },
  { label: "Home Depot", value: "NYSE:HD" },
  { label: "Merck & Co.", value: "NYSE:MRK" },
  { label: "Chevron", value: "NYSE:CVX" },
  { label: "Walmart", value: "NYSE:WMT" },
  { label: "Bank of America", value: "NYSE:BAC" },
  { label: "Coca-Cola", value: "NYSE:KO" },
  { label: "Oracle", value: "NYSE:ORCL" },
  { label: "McDonald's", value: "NYSE:MCD" },
  { label: "Salesforce", value: "NYSE:CRM" },
  { label: "Pfizer", value: "NYSE:PFE" },
  { label: "Walt Disney", value: "NYSE:DIS" },
  { label: "Caterpillar", value: "NYSE:CAT" },
  { label: "Goldman Sachs", value: "NYSE:GS" },
  { label: "IBM", value: "NYSE:IBM" },
  { label: "American Express", value: "NYSE:AXP" },
  { label: "General Electric", value: "NYSE:GE" },
  { label: "Boeing", value: "NYSE:BA" },
  { label: "3M", value: "NYSE:MMM" },
  { label: "Nike", value: "NYSE:NKE" },
  { label: "Starbucks", value: "NYSE:SBUX" },
  { label: "Morgan Stanley", value: "NYSE:MS" },
  { label: "Ford Motor Company", value: "NYSE:F" },
  { label: "General Motors", value: "NYSE:GM" },
];

// 為替 (FX)
export const fxSymbols = [
  { label: "米ドル/円", value: "FX:USDJPY" },
  { label: "ユーロ/円", value: "FX:EURJPY" },
  { label: "英ポンド/円", value: "FX:GBPJPY" },
  { label: "豪ドル/円", value: "FX:AUDJPY" },
  { label: "メキシコペソ/円", value: "FX:MXNJPY" },
  { label: "ユーロ/米ドル", value: "FX:EURUSD" },
  { label: "ランド/円", value: "FX:ZARJPY" },
  { label: "NZドル/円", value: "FX:NZDJPY" },
  { label: "ブラジルレアル/円", value: "FX:BRLJPY" },
  { label: "豪ドル/米ドル", value: "FX:AUDUSD" },
  { label: "ユーロ/豪ドル", value: "FX:EURAUD" },
  { label: "英ポンド/米ドル", value: "FX:GBPUSD" },
  { label: "カナダドル/円", value: "FX:CADJPY" },
  { label: "スイスフラン/円", value: "FX:CHFJPY" },
  { label: "シンガポールドル/円", value: "FX:SGDJPY" },
  { label: "香港ドル/円", value: "FX:HKDJPY" },
  { label: "フィリピンペソ/円", value: "FX:PHPJPY" },
  { label: "ベトナムドン/円", value: "FX:VNDJPY" },
  { label: "台湾ドル/円", value: "FX:TWDJPY" },
  { label: "トルコリラ/円", value: "FX:TRYJPY" },
  { label: "インドネシアルピア/円", value: "FX:IDRJPY" },
  { label: "ロシアルーブル/円", value: "FX:RUBJPY" },
  { label: "インドルピー/円", value: "FX:INRJPY" },
  { label: "スウェーデンクローナ/円", value: "FX:SEKJPY" },
  { label: "ノルウェークローネ/円", value: "FX:NOKJPY" },
  { label: "デンマーククローネ/円", value: "FX:DKKJPY" },
  { label: "ポーランドズロチ/円", value: "FX:PLNJPY" },
  { label: "マレーシアリンギット/円", value: "FX:MYRJPY" },
  { label: "タイバーツ/円", value: "FX:THBJPY" },
  { label: "韓国ウォン/円", value: "FX:KRWJPY" },
  { label: "中国人民元/円", value: "FX:CNHJPY" },
  { label: "NZドル/スイスフラン", value: "FX:NZDCHF" },
  { label: "豪ドル/スイスフラン", value: "FX:AUDCHF" },
  { label: "英ポンド/スイスフラン", value: "FX:GBPCHF" },
  { label: "米ドル/スイスフラン", value: "FX:USDCHF" },
  { label: "英ポンド/NZドル", value: "FX:GBPNZD" },
];

// インデックス
export const indexSymbols = [
  { label: "日経平均 (Nikkei 225)", value: "NIKKEI225" },
  { label: "TOPIX", value: "TOPIX" },
  { label: "S&P 500", value: "SP:SPX" },
  { label: "NASDAQ 100", value: "NASDAQ:NDX" },
  { label: "ダウ平均 (DJI)", value: "DJ:DJI" },
  { label: "ラッセル 2000", value: "RUSSELL:RUT" },
  { label: "ドイツ DAX", value: "XETR:DAX" },
  { label: "イギリス FTSE 100", value: "TVC:UKX" },
  { label: "フランス CAC 40", value: "EURONEXT:PX1" },
  { label: "香港ハンセン指数", value: "HSI:HSI" },
  { label: "上海総合指数", value: "SSE:000001" },
];

// すべての銘柄を結合したリスト（オプション）
export const allSymbols = [
  ...nikkei225Symbols,
  ...usStockSymbols,
  ...fxSymbols,
  ...indexSymbols,
];
